template-repository: "tschm/latex"
template-branch: "main"
include: |
  .github
  templates
  .gitignore
  .markdownlint.json
  .editorconfig
  .pre-commit-config.yaml
  Makefile
exclude: |
  .github/workflows/latex.yml
