name: LaTeX

on:
  push

permissions:
  contents: write

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: tschm/cradle/actions/latex@v0.1.52
        with:
          paper: paper/document.tex
          draft: draft

      # add or remove papers here
