# Workflow to build and release project artifacts
# This workflow is manually triggered via the GitHub UI

name: Build and Release

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)
  packages: write  # Allows the workflow to write to GitHub Packages (for Docker images)

jobs:
  # Job to set the tag based on input
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.set_tag.outputs.tag }}  # Output the tag to be used by other jobs

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

      # Create a GitHub release for the tag
      # This creates a release on GitHub with automatically generated release notes
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.3.2  # Third-party release action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
          tag_name: ${{ github.event.inputs.tag }}  # Use the provided tag
          generate_release_notes: true  # Automatically generate notes from commits


  # Job to build and publish LaTeX document (only included if use_latex is true)
  latex:
    runs-on: ubuntu-latest
    needs: tagging  # This job depends on the tagging job
    steps:
      - name: "Output tag"
        run: |
          echo "Tag: ${{ needs.tagging.outputs.new_tag }}"  # Print the new tag

      - name: "Build and publish the LaTeX document"
        uses: tschm/cradle/actions/latex@v0.2.0  # Custom action to build LaTeX documents
        with:
          paper: paper/document.tex  # Path to the LaTeX document to build
          tag: ${{ needs.tagging.outputs.new_tag }}  # Tag from the tagging job
