# Workflow to automatically bump the version, create a new tag, and publish LaTeX documents
# This workflow is manually triggered via the GitHub UI

name: Bump version and publish

on:
  workflow_dispatch:  # Manual trigger

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags and publish documents)

jobs:
  # Job to generate a new version tag
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}  # Output the new tag to be used by other jobs

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.81  # Custom action to generate a new tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

  # Job to build and publish the LaTeX document with the new tag
  latex:
    runs-on: ubuntu-latest
    needs: tagging  # This job depends on the tagging job
    steps:
      - name: "Output tag"
        run: |
          echo "Tag: ${{ needs.tagging.outputs.new_tag }}"  # Print the new tag

      - name: "Build and publish the LaTeX document"
        uses: tschm/cradle/actions/latex@main  # Custom action to build LaTeX documents
        with:
          paper: paper/document.tex  # Path to the LaTeX document to build
          tag: ${{ needs.tagging.outputs.new_tag }}  # Tag from the tagging job
