name: "book"

on:
- push


jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2  # Dedicated action for loading .env files

      - uses: cvxgrp/.github/actions/uv/marimo@v2.0.3
        with:
          source_folder: ${{ env.MARIMO_FOLDER }}

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2  # Dedicated action for loading .env files

      - uses: cvxgrp/.github/actions/uv/pdoc@v2.0.3
        with:
          source-folder: ${{ env.SOURCE_FOLDER }}


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2  # Dedicated action for loading .env files

      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.3
        with:
          tests-folder: ${{ env.TESTS_FOLDER }}
          source-folder: ${{ env.SOURCE_FOLDER }}

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/jupyter@v2.0.3

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/book@v2.0.3
