name: Bump Version

on:
  workflow_run:
    workflows: ["CI"]  # The name of your CI workflow
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
            github.ref == 'refs/heads/main' }}  # Ensure CI passed and we are on main branch
    steps:
      - name: Generate Tag
        uses: cvxgrp/.github/actions/tag@v2.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'
